### Data Preparation

1. **Import Libraries**: Start by importing necessary libraries such as pandas, numpy, and any other libraries required for data manipulation and analysis.

```python

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt

2. **Importing Dataset**

In [71]:
df = pd.read_csv('marketing_campaign.csv', sep='\t') 
df.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

The dataset, sourced from Kaggle (), is imported using Pandas and stored in a DataFrame.

3. **Check the Dataset**: missing values, data types,duplicate values and basic statistics.

In [4]:
print(df.shape)
print(df.columns)
print(df.info())

(2240, 29)
Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB
None

In [5]:
print(df.duplicated().sum())
df.isnull().sum()

0

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

Missing values in the numeric column `Income` are imputed with the column’s mean value.

In [7]:
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')

In [8]:
# check unique value for all columns
for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

ID: 2240
Year_Birth: 59
Education: 5
Marital_Status: 8
Income: 1974
Kidhome: 3
Teenhome: 3
Dt_Customer: 663
Recency: 100
MntWines: 776
MntFruits: 158
MntMeatProducts: 558
MntFishProducts: 182
MntSweetProducts: 177
MntGoldProds: 213
NumDealsPurchases: 15
NumWebPurchases: 15
NumCatalogPurchases: 14
NumStorePurchases: 14
NumWebVisitsMonth: 16
AcceptedCmp3: 2
AcceptedCmp4: 2
AcceptedCmp5: 2
AcceptedCmp1: 2
AcceptedCmp2: 2
Complain: 2
Z_CostContact: 1
Z_Revenue: 1
Response: 2

**Data Cleaning and Transforming**

Next, we inspect all columns for null or missing values while also verifying the data types of each column.

- missing = [ Income = 24]

4. **Dropping Unnecessary Columns**

In [72]:
df = df.drop(['ID',  'Z_CostContact', 'Z_Revenue'], axis=1)

5. **Fill Missing Values**: For columns with missing values, decide on a strategy to fill them (e.g., mean, median, mode, or a specific value).

- Check kind of missing values (MCAR, MAR,or MNAR)

In [73]:
import plotly.graph_objects as go

# Original data
df_income_all = df.copy()

# Data after dropping missing Income
df_income_dropped = df.dropna(subset=['Income'])

In [ ]:
fig_income = go.Figure()

# Before dropping NA
fig_income.add_trace(
    go.Histogram(
        x=df_income_all['Income'],
        name="Before dropping NA",
        showlegend=True
    )
)

# After dropping NA
fig_income.add_trace(
    go.Histogram(
        x=df_income_dropped['Income'],
        name="After dropping NA",
        showlegend=True,
        visible="legendonly"   # cleaner interaction
    )
)

fig_income.update_layout(
    barmode='overlay',
    title="Income Distribution Before and After Removing Missing Values",
    xaxis=dict(title="Income"),
    yaxis=dict(title="Count"),              
    width=600,
    height=450
)

fig_income.update_traces(opacity=0.6)

fig_income.show()

Basedo on overlay histograms it seems that the distribution very similar, the missing values in the Income column are likely MCAR (Missing Completely at Random). 

Therefore, removing records with missing income values is unlikely to introduce bias into the analysis.

- TEsting: Compare Distributions of OTHER VARIABLES

In [80]:
df['Income_missing'] = df['Income'].isna()

In [88]:
fig = go.Figure()

fig.add_trace(go.Histogram(
    x=df.loc[df['Income_missing'] == False, 'total_purchases'],
    name="Income Observed"
))

fig.add_trace(go.Histogram(
    x=df.loc[df['Income_missing'] == True, 'total_purchases'],
    name="Income Missing",
    visible="legendonly"
))

fig.update_layout(
    barmode='overlay',
    title="Total Purchases Distribution by Income Missingness",
    xaxis_title="Total Purchases",
    yaxis_title="Count"
)

fig.update_traces(opacity=0.6)
fig.show()

In [ ]:
# statistical test 
from scipy.stats import ks_2samp

vars_to_check = ['expenses', 'total_purchases', 'kids']

for v in vars_to_check:
    x1 = df.loc[df['Income_missing'] == False, v].dropna()
    x2 = df.loc[df['Income_missing'] == True, v].dropna()
    
    stat, p = ks_2samp(x1, x2)
    print(f"{v}: KS p-value = {p:.4f}")

# evidence: simmilar distributions and p > 0.05 => MCAR safe to drop

expenses: KS p-value = 0.4846
total_purchases: KS p-value = 0.6020
kids: KS p-value = 0.8226

- Columns understanding

In [14]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

Year_Birth: 59
Education: 5
Marital_Status: 8
Income: 1974
Kidhome: 3
Teenhome: 3
Dt_Customer: 663
Recency: 100
MntWines: 776
MntFruits: 158
MntMeatProducts: 558
MntFishProducts: 182
MntSweetProducts: 177
MntGoldProds: 213
NumDealsPurchases: 15
NumWebPurchases: 15
NumCatalogPurchases: 14
NumStorePurchases: 14
NumWebVisitsMonth: 16
AcceptedCmp3: 2
AcceptedCmp4: 2
AcceptedCmp5: 2
AcceptedCmp1: 2
AcceptedCmp2: 2
Complain: 2
Response: 2

- Cleaning consistent values

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year_Birth           2240 non-null   int64
 1   Education            2240 non-null   object
 2   Marital_Status       2240 non-null   object
 3   Income               2216 non-null   float64
 4   Kidhome              2240 non-null   int64
 5   Teenhome             2240 non-null   int64
 6   Dt_Customer          2240 non-null   datetime64[ns]
 7   Recency              2240 non-null   int64
 8   MntWines             2240 non-null   int64
 9   MntFruits            2240 non-null   int64
 10  MntMeatProducts      2240 non-null   int64
 11  MntFishProducts      2240 non-null   int64
 12  MntSweetProducts     2240 non-null   int64
 13  MntGoldProds         2240 non-null   int64
 14  NumDealsPurchases    2240 non-null   int64
 15  NumWebPurchases      2240 non-null   int64
 16  NumCatalogPurchases  2240 non-null   int64
 17  NumStorePurchases    2240 non-null   int64
 18  NumWebVisitsMonth    2240 non-null   int64
 19  AcceptedCmp3         2240 non-null   int64
 20  AcceptedCmp4         2240 non-null   int64
 21  AcceptedCmp5         2240 non-null   int64
 22  AcceptedCmp1         2240 non-null   int64
 23  AcceptedCmp2         2240 non-null   int64
 24  Complain             2240 non-null   int64
 25  Response             2240 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(22), object(2)
memory usage: 455.1+ KB

- converting time values

In [ ]:
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], format='%d-%m-%Y')

In [37]:
df['Year_Birth'].describe()

count    2240.000000
mean     1968.805804
std        11.984069
min      1893.000000
25%      1959.000000
50%      1970.000000
75%      1977.000000
max      1996.000000
Name: Year_Birth, dtype: float64

In [51]:
mean = df['Year_Birth'].mean()
max = df['Year_Birth'].max()
min = df['Year_Birth'].min()
std = df['Year_Birth'].std()
age = 2014 - df['Year_Birth'] 
age.describe()

# print(f"Mean: {mean}, Max: {max}, Min: {min}, Std: {std}")

count    2240.000000
mean       45.194196
std        11.984069
min        18.000000
25%        37.000000
50%        44.000000
75%        55.000000
max       121.000000
Name: Year_Birth, dtype: float64

- Standardize column names

In [52]:
df['Marital_Status'].unique()
# Alone, Absurd, YOLO -> single 
df['Marital_Status'] = df['Marital_Status'].replace({
    'Alone': 'Single', 
    'Absurd': 'Single',
    'YOLO': 'Single'})
df['Marital_Status'].value_counts()

Marital_Status
Married     864
Together    580
Single      487
Divorced    232
Widow        77
Name: count, dtype: int64

In [85]:
# kid 
df['kids'] = df['Kidhome']+ df['Teenhome'] 
# purchases 
df['total_purchases'] = df['NumWebPurchases'] + df['NumCatalogPurchases'] + df['NumStorePurchases'] + df['NumWebVisitsMonth']
# expense 
df['expenses']= df['MntWines'] + df['MntFruits'] + df['MntMeatProducts'] + df['MntFishProducts'] + df['MntSweetProducts'] + df['MntGoldProds']
# total accepted campaigns
df['total_accepted_campaigns'] = df['AcceptedCmp1'] + df['AcceptedCmp2'] + df['AcceptedCmp3'] + df['AcceptedCmp4'] + df['AcceptedCmp5'] + df['Response']
df['age'] = 2014 - df['Year_Birth']
df[['kids', 'total_purchases', 'expenses', 'total_accepted_campaigns','age']].head()

   kids  total_purchases  expenses  total_accepted_campaigns  age
0     0               29      1617                         1   57
1     2                9        27                         0   60
2     0               24       776                         0   49
3     1               12        53                         0   30
4     1               19       422                         0   33

In [86]:
df.columns

Index(['Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Response', 'Income_missing', 'kids',
       'total_purchases', 'expenses', 'total_accepted_campaigns', 'age'],
      dtype='object')

In [60]:
df['MntFruits'].describe()

count    2240.000000
mean       26.302232
std        39.773434
min         0.000000
25%         1.000000
50%         8.000000
75%        33.000000
max       199.000000
Name: MntFruits, dtype: float64

In [61]:
df['NumCatalogPurchases'].describe()

count    2240.000000
mean        2.662054
std         2.923101
min         0.000000
25%         0.000000
50%         2.000000
75%         4.000000
max        28.000000
Name: NumCatalogPurchases, dtype: float64

In [ ]:
df['Recency'].describe() # Number of days since customer’s last purchase

count    2240.000000
mean       49.109375
std        28.962453
min         0.000000
25%        24.000000
50%        49.000000
75%        74.000000
max        99.000000
Name: Recency, dtype: float64

New collumns: kis, total_purchases, expenses, total_accepted_campaigns

In [64]:

# df1 = df[['Education', 'Marital_Status','Income', 'kids', 'total_purchases', 'expenses', 'total_accepted_campaigns','Recency','age']]

In [68]:
df2= df[['Education', 'Marital_Status','age', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2','Response']]

In [70]:
df2.describe().T

,count,mean,min,25%,50%,75%,max,std
age,2240.0,45.194196,18.0,37.0,44.0,55.0,121.0,11.984069
Income,2216.0,52247.251354,1730.0,35303.0,51381.5,68522.0,666666.0,25173.076661
Kidhome,2240.0,0.444196,0.0,0.0,0.0,1.0,2.0,0.538398
Teenhome,2240.0,0.50625,0.0,0.0,0.0,1.0,2.0,0.544538
Dt_Customer,2240,2013-07-10 10:01:42.857142784,2012-07-30 00:00:00,2013-01-16 00:00:00,2013-07-08 12:00:00,2013-12-30 06:00:00,2014-06-29 00:00:00,NaN
Recency,2240.0,49.109375,0.0,24.0,49.0,74.0,99.0,28.962453
MntWines,2240.0,303.935714,0.0,23.75,173.5,504.25,1493.0,336.597393
MntFruits,2240.0,26.302232,0.0,1.0,8.0,33.0,199.0,39.773434
MntMeatProducts,2240.0,166.95,0.0,16.0,67.0,232.0,1725.0,225.715373
MntFishProducts,2240.0,37.525446,0.0,3.0,12.0,50.0,259.0,54.628979
MntSweetProducts,2240.0,27.062946,0.0,1.0,8.0,33.0,263.0,41.280498
MntGoldProds,2240.0,44.021875,0.0,9.0,24.0,56.0,362.0,52.167439
NumDealsPurchases,2240.0,2.325,0.0,1.0,2.0,3.0,15.0,1.932238
NumWebPurchases,2240.0,4.084821,0.0,2.0,4.0,6.0,27.0,2.778714
NumCatalogPurchases,2240.0,2.662054,0.0,0.0,2.0,4.0,28.0,2.923101
NumStorePurchases,2240.0,5.790179,0.0,3.0,5.0,8.0,13.0,3.250958
NumWebVisitsMonth,2240.0,5.316518,0.0,3.0,6.0,7.0,20.0,2.426645
AcceptedCmp3,2240.0,0.072768,0.0,0.0,0.0,0.0,1.0,0.259813
AcceptedCmp4,2240.0,0.074554,0.0,0.0,0.0,0.0,1.0,0.262728
AcceptedCmp5,2240.0,0.072768,0.0,0.0,0.0,0.0,1.0,0.259813
AcceptedCmp1,2240.0,0.064286,0.0,0.0,0.0,0.0,1.0,0.245316
AcceptedCmp2,2240.0,0.013393,0.0,0.0,0.0,0.0,1.0,0.114976
Response,2240.0,0.149107,0.0,0.0,0.0,0.0,1.0,0.356274

Dataset context: 
- Demographics: Age, Education, Marital Status, Income, Children
- Spending: Wine, Meat, Fish, Fruits, Gold products
- Behavior: Recency, purchase channels (web/store/catalog)
- Marketing: Campaign acceptance, complaints

### Customer Segmentation Based on Purchasing Behavior and Demographics
Q1: Can customers be grouped into distinct segments based on their demographic characteristics and spending behavior?
-> Goal: To identify meaningful customer segments to support targeted marketing strategies.
- EDA
- PCA (dimensionality reduction)
- K-Means / Hierarchical clustering
- Cluster profiling

In [42]:
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], format='%d-%m-%Y')

In [43]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
num_cols

Index(['Year_Birth', 'Income', 'Kidhome', 'Teenhome', 'Recency', 'MntWines',
       'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')

In [ ]:
# Demographic Information Columns:

# ID: Customer’s unique identifier
# Year_Birth: Customer’s birth year
# Education: Customer’s education level
# Marital_Status: Customer’s marital status
# Income: Customer’s yearly household income
# Kidhome: Number of children in customer’s household
# Teenhome: Number of teenagers in customer’s household
# Dt_Customer: Date of customer’s enrollment with the company
# Recency: Number of days since customer’s last purchase
# Complain: 1 if customer complained in the last 2 years, 0 otherwise

In [44]:
cat_cols = df.select_dtypes('object')
cat_cols

       Education Marital_Status
0     Graduation         Single
1     Graduation         Single
2     Graduation       Together
3     Graduation       Together
4            PhD        Married
...          ...            ...
2235  Graduation        Married
2236         PhD       Together
2237  Graduation       Divorced
2238      Master       Together
2239         PhD        Married

[2240 rows x 2 columns]

In [45]:
df['NumCatalogPurchases'].unique()

array([10,  1,  2,  0,  3,  4,  6, 28,  9,  5,  8,  7, 11, 22],
      dtype=int64)

In [46]:
for col in cat_cols:
    count = df[col].value_counts()
    print(count)
    print('---')

Education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64
---
Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64
---

In [22]:
# How do the number of kids/teenagers in a household affect how that household shops?
# number of kids/teenagers vs total purchases 

df['Kidhome'].unique()

array([0, 1, 2], dtype=int64)

In [23]:
df['Teenhome'].unique()

array([0, 1, 2], dtype=int64)

In [47]:
# Standardize column names 
df['Marital_Status'].unique()
# Alone, Absurd, YOLO -> single 
df['Marital_Status'] = df['Marital_Status'].replace({
    'Alone': 'Single', 
    'Absurd': 'Single',
    'YOLO': 'Single'})
df['Marital_Status'].value_counts()

Marital_Status
Married     864
Together    580
Single      487
Divorced    232
Widow        77
Name: count, dtype: int64

In [48]:
# kid 
df['kids'] = df['Kidhome']+ df['Teenhome'] 
# purchases 
df['total_purchases'] = df['NumWebPurchases'] + df['NumCatalogPurchases'] + df['NumStorePurchases'] + df['NumWebVisitsMonth']
# expense 
df['expenses']= df['MntWines'] + df['MntFruits'] + df['MntMeatProducts'] + df['MntFishProducts'] + df['MntSweetProducts'] + df['MntGoldProds']
# total accepted campaigns
df['total_accepted_campaigns'] = df['AcceptedCmp1'] + df['AcceptedCmp2'] + df['AcceptedCmp3'] + df['AcceptedCmp4'] + df['AcceptedCmp5'] + df['Response']

df[['kids', 'total_purchases', 'expenses', 'total_accepted_campaigns']].head()

   kids  total_purchases  expenses  total_accepted_campaigns
0     0               29      1617                         1
1     2                9        27                         0
2     0               24       776                         0
3     1               12        53                         0
4     1               19       422                         0

In [50]:
df.columns

Index(['Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response',
       'kids', 'total_purchases', 'expenses', 'total_accepted_campaigns'],
      dtype='object')

In [52]:

df1 = df[['Education', 'Marital_Status','Income', 'kids', 'total_purchases', 'expenses', 'total_accepted_campaigns']]
df1

,Education,Marital_Status,Income,kids,total_purchases,expenses,total_accepted_campaigns
0,Graduation,Single,58138.0,0,29,1617,1
1,Graduation,Single,46344.0,2,9,27,0
2,Graduation,Together,71613.0,0,24,776,0
3,Graduation,Together,26646.0,1,12,53,0
4,PhD,Married,58293.0,1,19,422,0
...,...,...,...,...,...,...,...
2235,Graduation,Married,61223.0,1,21,1341,0
2236,PhD,Together,64014.0,3,22,444,1
2237,Graduation,Divorced,56981.0,0,24,1241,1
2238,Master,Together,69245.0,1,24,843,0
2239,PhD,Married,52869.0,2,15,172,1

In [57]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Education                 2240 non-null   object
 1   Marital_Status            2240 non-null   object
 2   Income                    2216 non-null   float64
 3   kids                      2240 non-null   int64
 4   total_purchases           2240 non-null   int64
 5   expenses                  2240 non-null   int64
 6   total_accepted_campaigns  2240 non-null   int64
dtypes: float64(1), int64(4), object(2)
memory usage: 122.6+ KB

In [60]:
df1.corr(df.query.selected(include=['int64', 'float64']))

AttributeError: 'function' object has no attribute 'selected'

Cat : 
- goods vs education level  (Chi-Square tests)  
- marrital status vs (Chi-Square tests) 
- 
##  Customer segmentation 
+ Objective: 
- income and purchasing behavior 
- kids and hosehold spending patterns 
- use PCA + k-mean clustering